
openapi:
  path: /home/encima/dev/go/c3s-oape/swagger/openapi.json
server:
  staticDir: /home/encima/dev/go/c3s-oape/static/
  port: 6666
system-db:
  parent-stmt: 
  parent-fields:
    - id
    - created_at
    - modified_at
  reserved-words:
    - user
database:
  type: postgres
  conn: postgresql://test:test@localhost/openape
  required: true

