
raml:
  # path: /home/encima/dev/go/c3s-oape/api/root.raml
openapi:
  path: /home/encima/dev/go/c3s-oape/api/openapi.json
  src: FILE
server:
  staticDir: /home/encima/dev/go/c3s-oape/static/
system-db:
  parent-stmt: 
  parent-fields:
    - id
    - created_at
    - modified_at
  reserved-words:
    - user
database:
  type: postgres
  conn: postgresql://test:test@localhost/openape?sslmode=disable
  required: true

