#%RAML 1.0
---
title: Openape API
baseUri: http://{host}:{port}/{basePath}{version}
version: v1
baseUriParameters: 
  port: 
    type: int
    default: 8080
  basePath: 
    type: string
    default: api/
  host: 
    type: string
    default: localhost
protocols: [ HTTP, HTTPS ]
mediaType: application/json
types:
  Users: !include types/user.json
  Projects: !include types/project.json
resourceTypes: 
  users:
    type: Users
/users:
  type: users
  get:
    description: "Get a list of Users"
    responses: 
      200:
        body:
          type: array
          items: 
            type: users
  post:
    description: "Create User"
    body:
      type: users
    responses: 
      201:
        body:
          type: users
  /login:
    type: users
    post:
      description: Allow a user to login
      responses:
        404:
          description: User not found
        200:
          body:
            type: users




